default_stages: [ pre-commit, pre-push ]
repos:

  - repo: local
    hooks:
      - id: code-format
        name: code-format
        types: [ python ]
        pass_filenames: false
        language: system
        entry: poetry run -- nox -s format:fix
        stages: [ pre-commit ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        stages: [ pre-commit ]
      - id: end-of-file-fixer
        stages: [ pre-commit ]
      - id: trailing-whitespace
        stages: [ pre-commit ]

  - repo: local
    hooks:
      - id: type-check
        name: type-check
        types: [ python ]
        pass_filenames: false
        language: system
        entry: poetry run -- nox -s lint:typing
        stages: [ pre-push ]

  - repo: local
    hooks:
      - id: lint
        name: lint
        types: [ python ]
        pass_filenames: false
        language: system
        entry: poetry run -- nox -s lint:code
        stages: [ pre-push ]
