language: python

cache: pip

matrix:
    include:
        -   python: 3.6
            env: EXASOL_TAG=6.2.5-d1
        -   python: 3.6
            env: EXASOL_TAG=6.1.9-d1
        -   python: 3.6
            env: EXASOL_TAG=6.0.16-d1
        -   python: 3.7
            env: EXASOL_TAG=6.2.5-d1
            dist: xenial
        -   python: 3.7
            env: EXASOL_TAG=6.1.9-d1
            dist: xenial
        -   python: 3.7
            env: EXASOL_TAG=6.0.16-d1
            dist: xenial
        -   python: 3.8
            env: EXASOL_TAG=6.2.5-d1
            dist: xenial
        -   python: 3.8
            env: EXASOL_TAG=6.1.9-d1
            dist: xenial
        -   python: 3.8
            env: EXASOL_TAG=6.0.16-d1
            dist: xenial

services:
  - docker

warnings_are_errors: false

env:
  global:
    - EXAHOST="127.0.0.1:8563"

before_install:
    - docker run --detach --name exasol --privileged -p 127.0.0.1:8563:8888 exasol/docker-db:$EXASOL_TAG

install:
    - sleep 120
    - docker logs exasol

    - pip install -e .[pandas,encrypt,ujson,rapidjson,examples]

script:
    - python examples/00_prepare.py
    - python examples/01_basic.py
    - python examples/02_fetch_tuple.py
    - python examples/03_fetch_dict.py
    - python examples/04_fetch_mapper.py
    - python examples/05_formatting.py
    - python examples/06_pandas.py
    - python examples/07_import_export.py
    - python examples/08_transaction.py
    - python examples/09_exceptions.py
    - python examples/10_redundancy.py
    - python examples/11_edge_case.py
    - python examples/12_db2_compat.py
    - python examples/13_ext.py
    - python examples/14_parallel_export.py
    - python examples/15_encryption.py
    - python examples/16_ujson.py
    - python examples/17_rapidjson.py
    - python examples/18_session_params.py
    - python examples/19_local_config.py
    - python examples/20_parallel_import.py
    - python examples/21_parallel_export_import.py
    - python examples/22_profiling.py
    - python examples/23_snapshot_transactions.py
    - python examples/24_script_output.py
    - python examples/25_overload.py
    - python examples/26_quote_ident.py
    - python examples/27_abort_query.py
    - python examples/28_thread_safety.py
    - python examples/29_dsn_parsing.py
    - python examples/30_http_proxy.py
    - python examples/31_context_manager.py
    - python examples/32_insert_multi.py
    - python examples/33_meta.py
    - python examples/34_http_transport_errors.py
    - python examples/35_garbage_collection.py
    - python examples/36_meta_nosql.py
