name: Build Matrix (All Versions)

on:
  workflow_call:
    outputs:
      matrix:
        description: "Generates the all versions build matrix"
        value: ${{ jobs.all_versions.outputs.matrix }}

jobs:
  all_versions:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: SCM Checkout
        uses: actions/checkout@v5

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v1

      - name: Generate matrix
        run: poetry run -- nox -s matrix:all

      - id: set-matrix
        run: |
          echo "matrix=$(poetry run -- nox -s matrix:all)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
