name: Build Matrix (Python)

on:
  workflow_call:
    outputs:
      matrix:
        description: "Generates the python version build matrix"
        value: ${{ jobs.set-matrix-python.outputs.matrix }}

jobs:
  set-matrix-python:
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    steps:
      - name: Check out Repository
        id: check-out-repository
        uses: actions/checkout@v6

      - name: Set up Python & Poetry Environment
        id: set-up-python-and-poetry-environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v6
        with:
          python-version: "3.10"
          poetry-version: "2.3.0"

      - name: Generate Matrix
        id: generate-matrix
        run: poetry run -- nox -s matrix:python

      - name: Set Matrix
        id: set-matrix
        run: |
          echo "matrix=$(poetry run -- nox -s matrix:python)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
