name: Build Matrix (Exasol)

on:
  workflow_call:
    outputs:
      matrix:
        description: "Generates the exasol version build matrix"
        value: ${{ jobs.set-matrix-exasol.outputs.matrix }}

jobs:
  set-matrix-exasol:
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    steps:
      - name: Check out Repository
        id: check-out-repository
        uses: actions/checkout@v6

      - name: Set up Python & Poetry Environment
        id: set-up-python-and-poetry-environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v6
        with:
          python-version: "3.10"
          poetry-version: "2.3.0"

      - name: Generate Matrix
        id: generate-matrix
        run: poetry run -- nox -s matrix:exasol

      - name: Set Matrix
        id: set-matrix
        run: |
          echo "matrix=$(poetry run -- nox -s matrix:exasol)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
